name: Github Pages

on:
    push:
        tags:
            - 'v*'

jobs:
    github-pages:
        name: 'Github Pages'
        runs-on: ubuntu-latest

        steps:
            - name: Setup NodeJS
              uses: actions/setup-node@v2.4.1
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org/

            - name: Checkout
              uses: actions/checkout@v2.4.0

            - run: npm ci
            - run: npm run build:example

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3.7.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: github-pages
                  publish_dir: ./example/dist
                  destination_dir: ./
